name: check
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    if: github.actor != 'bitdriftlabs-terraform[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install flatc
        run: sudo apt-get update && sudo apt-get install -y flatbuffers-compiler
      - uses: bufbuild/buf-action@v1
        with:
          setup_only: true
      - uses: bufbuild/buf-lint-action@v1
      - name: Check FlatBuffers
        shell: bash
        run: |
          set -euo pipefail
          shopt -s globstar nullglob
          schemas=(src/**/*.fbs)
          if ((${#schemas[@]} == 0)); then
            echo "No FlatBuffer schemas found"
            exit 1
          fi
          temp_dir="$(mktemp -d)"

          flatc --cpp -I src -o "$temp_dir" "${schemas[@]}"
      - name: Format
        run: tools/format.sh
      - name: Check license
        run: tools/check_license.sh
